use std::str::FromStr;
use super::*;

grammar;

pub Expression: Box<Expression> = {
    Var => Box::new(Expression::Var(<>)),
    Fun,
    Int => Box::new(Expression::Int(<>)),
};

Fun: Box<Expression> = {
    <Var> <Expression> => Box::new(Expression::Fun(<>)) 
};

Var: String = {
    r"[a-zA-Z_][a-zA-Z0-9_]*" => (<>).to_owned(),
};

Int: i32 = {
    <s:r"[0-9]+"> => i32::from_str(s).unwrap()    
};
